In [5]:
import os

# Confirm file really exists where you're looking
file_path = "zoomcamp_pipeline.duckdb"
print("‚úÖ Exists:", os.path.exists(file_path))
print("üìç Absolute Path:", os.path.abspath(file_path))

‚úÖ Exists: True
üìç Absolute Path: /workspaces/llm-datatalk/03/zoomcamp_pipeline.duckdb

In [16]:
import duckdb
con = duckdb.connect("/workspaces/llm-datatalk/03/zoomcamp_pipeline.duckdb")
print(con.execute("SHOW DATABASES").fetchall())

[('zoomcamp_pipeline',)]

In [20]:
# Query using schema-qualified table name
df = con.execute("SELECT * FROM zoomcamp_tagged_data.zoomcamp_data LIMIT 50").df()
df

,end_lat,end_lon,fare_amt,passenger_count,payment_type,start_lat,start_lon,tip_amt,tolls_amt,total_amt,trip_distance,trip_dropoff_date_time,trip_pickup_date_time,store_and_forward,surcharge,vendor_name,tag,rate_code,mta_tax
0,40.742963,-73.980072,45.0,1,Credit,40.641525,-73.787442,9.00,4.15,58.15,17.52,2009-06-14 23:48:00,2009-06-14 23:23:00,NaN,0.0,VTS,second_10_days,None,None
1,40.740187,-74.005698,6.5,1,Credit,40.722065,-74.009767,1.00,0.00,8.50,1.56,2009-06-18 17:43:00,2009-06-18 17:35:00,NaN,1.0,VTS,second_10_days,None,None
2,40.718043,-74.004745,12.5,5,Credit,40.761945,-73.983038,2.00,0.00,15.50,3.37,2009-06-10 18:27:00,2009-06-10 18:08:00,NaN,1.0,VTS,second_10_days,None,None
3,40.739637,-73.985233,4.9,1,CASH,40.749802,-73.992247,0.00,0.00,5.40,1.11,2009-06-14 23:58:00,2009-06-14 23:54:00,NaN,0.5,VTS,second_10_days,None,None
4,40.730032,-73.852693,25.7,1,CASH,40.776825,-73.949233,0.00,4.15,29.85,11.09,2009-06-13 13:23:00,2009-06-13 13:01:00,NaN,0.0,VTS,second_10_days,None,None
5,40.777537,-73.976860,7.3,2,Credit,40.790582,-73.953652,2.00,0.00,10.30,2.10,2009-06-10 19:52:00,2009-06-10 19:43:00,NaN,1.0,VTS,second_10_days,None,None
6,40.770277,-73.962125,3.7,1,Credit,40.767147,-73.966408,1.00,0.00,5.20,0.40,2009-06-10 20:09:00,2009-06-10 20:06:00,NaN,0.5,VTS,second_10_days,None,None
7,40.774043,-73.951465,8.1,2,CASH,40.761750,-73.977773,0.00,0.00,8.60,2.24,2009-06-14 21:08:00,2009-06-14 20:57:00,NaN,0.5,VTS,second_10_days,None,None
8,40.777985,-73.943683,6.1,1,CASH,40.766355,-73.959832,0.00,0.00,6.10,1.48,2009-06-14 12:56:00,2009-06-14 12:49:00,NaN,0.0,VTS,second_10_days,None,None
9,40.720052,-74.009823,8.9,1,CASH,40.751327,-73.987588,0.00,0.00,9.90,2.72,2009-06-10 18:13:00,2009-06-10 18:03:00,NaN,1.0,VTS,second_10_days,None,None
10,40.758588,-73.981827,4.1,5,CASH,40.764112,-73.988610,0.00,0.00,4.10,0.69,2009-06-14 11:27:00,2009-06-14 11:24:00,NaN,0.0,VTS,second_10_days,None,None
11,40.727343,-73.993425,2.5,4,Credit,40.727343,-73.993425,4.00,0.00,6.50,0.00,2009-06-13 19:17:00,2009-06-13 19:17:00,NaN,0.0,VTS,second_10_days,None,None
12,40.763403,-73.982693,2.9,1,CASH,40.763875,-73.982592,0.00,0.00,3.90,0.05,2009-06-10 19:39:00,2009-06-10 19:38:00,NaN,1.0,VTS,second_10_days,None,None
13,40.881595,-73.864513,33.3,2,CASH,40.759188,-73.992023,0.00,0.00,33.80,14.86,2009-06-14 03:00:00,2009-06-14 02:34:00,NaN,0.5,VTS,second_10_days,None,None
14,40.741075,-73.986537,4.1,5,CASH,40.752078,-73.978600,0.00,0.00,4.10,0.88,2009-06-16 12:59:00,2009-06-16 12:56:00,NaN,0.0,VTS,second_10_days,None,None
15,40.728683,-73.981595,11.7,1,Credit,40.759070,-73.984905,4.00,0.00,15.70,2.82,2009-06-16 12:58:00,2009-06-16 12:39:00,NaN,0.0,VTS,second_10_days,None,None
16,40.745173,-73.998107,10.1,1,CASH,40.760320,-73.964637,0.00,0.00,10.60,2.83,2009-06-15 20:18:00,2009-06-15 20:05:00,NaN,0.5,VTS,second_10_days,None,None
17,40.779377,-73.987643,9.7,1,CASH,40.761615,-73.966648,0.00,0.00,9.70,2.08,2009-06-16 12:59:00,2009-06-16 12:44:00,NaN,0.0,VTS,second_10_days,None,None
18,40.761275,-73.972752,7.7,2,CASH,40.752203,-73.973720,0.00,0.00,8.70,0.80,2009-06-10 18:10:00,2009-06-10 17:57:00,NaN,1.0,VTS,second_10_days,None,None
19,40.749855,-73.993482,4.5,1,Credit,40.754173,-73.993775,1.00,0.00,5.50,0.58,2009-06-14 17:58:00,2009-06-14 17:53:00,NaN,0.0,VTS,second_10_days,None,None
20,40.741707,-74.004725,3.7,2,CASH,40.741090,-73.997960,0.00,0.00,3.70,0.48,2009-06-14 11:19:00,2009-06-14 11:16:00,NaN,0.0,VTS,second_10_days,None,None
21,40.761607,-73.969057,6.5,1,CASH,40.754082,-73.966080,0.00,0.00,7.50,0.90,2009-06-18 17:11:00,2009-06-18 17:02:00,NaN,1.0,VTS,second_10_days,None,None
22,40.764100,-73.982590,6.1,5,CASH,40.742647,-73.993013,0.00,0.00,6.10,1.81,2009-06-14 19:09:00,2009-06-14 19:04:00,NaN,0.0,VTS,second_10_days,None,None
23,40.772295,-73.966650,3.3,5,CASH,40.769087,-73.965202,0.00,0.00,4.30,0.32,2009-06-15 19:19:00,2009-06-15 19:17:00,NaN,1.0,VTS,second_10_days,None,None
24,40.756328,-73.964167,9.7,1,Credit,40.750137,-73.990920,2.00,0.00,12.70,2.18,2009-06-10 19:28:00,2009-06-10 19:13:00,NaN,1.0,VTS,second_10_days,None,None
25,40.739487,-73.999645,5.7,1,CASH,40.752395,-74.004405,0.00,0.00,6.20,1.35,2009-06-10 20:09:00,2009-06-10 20:03:00,NaN,0.5,VTS,second_10_days,None,None
26,40.714525,-73.997617,4.9,1,CASH,40.723430,-74.007843,0.00,0.00,5.40,0.95,2009-06-12 01:17:00,2009-06-12 01:13:00,NaN,0.5,VTS,second_10_days,None,None
27,40.747393,-74.003257,5.7,1,CASH,40.751342,-73.993282,0.00,0.00,5.70,0.78,2009-06-16 12:16:00,2009-06-16 12:08:00,NaN,0.0,VTS,second_10_days,None,None
28,40.736473,-73.978778,10.5,2,CASH,40.715570,-74.011020,0.00,0.00,11.00,3.17,2009-06-11 22:40:00,2009-06-11 22:26:00,NaN,0.5,VTS,second_10_days,None,None
29,40.759115,-73.978970,5.7,1,CASH,40.756065,-73.991100,0.00,0.00,6.20,0.94,2009-06-11 22:51:00,2009-06-11 22:44:00,NaN,0.5,VTS,second_10_days,None,None
30,40.758668,-73.990978,15.7,2,Credit,40.758737,-73.919247,3.92,0.00,19.62,5.04,2009-06-14 14:48:00,2009-06-14 14:27:00,NaN,0.0,VTS,second_10_days,None,None
31,40.717167,-73.998790,5.3,2,CASH,40.719118,-74.008793,0.00,0.00,5.80,0.95,2009-06-11 23:10:00,2009-06-11 23:04:00,NaN,0.5,VTS,second_10_days,None,None
32,40.728728,-74.007225,9.3,1,CASH,40.757450,-73.985397,0.00,0.00,10.30,2.35,2009-06-18 16:21:00,2009-06-18 16:08:00,NaN,1.0,VTS,second_10_days,None,None
33,40.752195,-73.977895,2.5,1,CASH,40.752195,-73.977895,0.00,0.00,3.50,0.00,2009-06-10 18:49:00,2009-06-10 18:48:00,NaN,1.0,VTS,second_10_days,None,None
34,40.763517,-73.965395,4.5,1,CASH,40.757270,-73.970070,0.00,0.00,5.50,0.57,2009-06-18 16:17:00,2009-06-18 16:12:00,NaN,1.0,VTS,second_10_days,None,None
35,40.643930,-73.782998,45.0,2,CASH,40.758123,-73.989907,0.00,5.00,50.00,16.91,2009-06-18 16:24:00,2009-06-18 15:15:00,NaN,0.0,VTS,second_10_days,None,None
36,40.731338,-74.005428,9.3,2,CASH,40.744898,-73.980695,0.00,0.00,9.30,2.11,2009-06-18 15:18:00,2009-06-18 15:02:00,NaN,0.0,VTS,second_10_days,None,None
37,40.716315,-74.012675,8.9,2,CASH,40.729900,-74.004068,0.00,0.00,9.90,1.71,2009-06-10 18:19:00,2009-06-10 18:06:00,NaN,1.0,VTS,second_10_days,None,None
38,40.748860,-73.988012,6.9,1,Credit,40.728555,-73.999718,2.00,0.00,9.40,1.88,2009-06-12 01:28:00,2009-06-12 01:20:00,NaN,0.5,VTS,second_10_days,None,None
39,40.780100,-73.950063,4.5,1,CASH,40.782180,-73.957393,0.00,0.00,5.50,0.51,2009-06-10 18:12:00,2009-06-10 18:07:00,NaN,1.0,VTS,second_10_days,None,None
40,40.805542,-73.961878,12.9,1,CASH,40.757243,-73.969688,0.00,0.00,13.90,4.33,2009-06-15 19:23:00,2009-06-15 19:06:00,NaN,1.0,VTS,second_10_days,None,None
41,40.752172,-73.971932,4.9,5,CASH,40.755125,-73.983062,0.00,0.00,5.40,0.90,2009-06-12 01:51:00,2009-06-12 01:46:00,NaN,0.5,VTS,second_10_days,None,None
42,40.687622,-73.957630,10.5,1,Credit,40.693903,-73.992148,2.00,0.00,13.00,3.05,2009-06-12 00:56:00,2009-06-12 00:42:00,NaN,0.5,VTS,second_10_days,None,None
43,40.766405,-73.988600,7.7,5,CASH,40.750982,-73.991153,0.00,0.00,7.70,0.03,2009-06-16 11:37:00,2009-06-16 11:23:00,NaN,0.0,VTS,second_10_days,None,None
44,40.762860,-73.984875,11.7,2,CASH,40.718950,-74.008722,0.00,0.00,12.20,3.37,2009-06-14 01:09:00,2009-06-14 00:53:00,NaN,0.5,VTS,second_10_days,None,None
45,40.782977,-73.973780,10.5,1,CASH,40.751155,-73.994300,0.00,0.00,10.50,2.60,2009-06-14 15:29:00,2009-06-14 15:14:00,NaN,0.0,VTS,second_10_days,None,None
46,40.768777,-73.967463,5.7,1,CASH,40.770840,-73.982300,0.00,0.00,5.70,1.26,2009-06-16 11:33:00,2009-06-16 11:26:00,NaN,0.0,VTS,second_10_days,None,None
47,40.716892,-74.012360,18.9,1,CASH,40.762633,-73.970215,0.00,0.00,19.90,7.28,2009-06-15 19:42:00,2009-06-15 19:24:00,NaN,1.0,VTS,second_10_days,None,None
48,40.757157,-73.981380,4.1,5,CASH,40.760952,-73.989045,0.00,0.00,4.10,0.43,2009-06-18 15:39:00,2009-06-18 15:35:00,NaN,0.0,VTS,second_10_days,None,None
49,40.761542,-73.982648,8.1,1,CASH,40.780972,-73.972577,0.00,0.00,8.10,1.57,2009-06-18 15:20:00,2009-06-18 15:07:00,NaN,0.0,VTS,second_10_days,None,None